#!/bin/bash

# دليل التثبيت السريع للترمكس
# Termux Quick Installation Guide

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   📖 دليل التثبيت السريع"
echo "   Quick Installation Guide"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🇦🇪 للمستخدمين العرب:"
echo "   اتبع الخطوات في ملف README_AR.md"
echo ""
echo "🇬🇧 For English users:"
echo "   Follow the steps in README.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "   🚀 التثبيت السريع / Quick Install"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  قم بتحديث الترمكس / Update Termux:"
echo "   pkg update && pkg upgrade -y"
echo ""
echo "2️⃣  ثبت Git / Install Git:"
echo "   pkg install git -y"
echo ""
echo "3️⃣  استنسخ المشروع / Clone the project:"
echo "   git clone https://github.com/obieda-hussien/OBI-BOT2.git"
echo "   cd OBI-BOT2"
echo ""
echo "4️⃣  شغل سكريبت التثبيت / Run install script:"
echo "   bash termux-install.sh"
echo ""
echo "5️⃣  شغل البوت / Start the bot:"
echo "   bash termux-start.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
